version: '3.9'

services:
  djanghi-api:
    build:
      context: .
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${API_IMAGE_NAME}
    command: gunicorn apps.wsgi:application --bind 0.0.0.0:8070 -w 4 -t 60
    volumes:
      - static_volume:/var/djanghi/static
    expose:
      - "8070"
    networks:
      - djanghi-network

  nginx:
    build: ./nginx
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${NGINX_IMAGE}
    volumes:
      - static_volume:/var/djanghi/static
    ports:
      - "80:80"
    depends_on:
      - djanghi-api
    networks:
      - djanghi-network

networks:
  djanghi-network:
    name: djanghi-network

volumes:
  static_volume:
