version: '3.9'

services:
  djanghi_api:
    build:
      context: .
    image: djanghi/prod
    command: gunicorn djanghi_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/djanghi/staticfiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/djanghi/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - djanghi_api

volumes:
  postgres_data:
  static_volume:
