version: '3.9'

services:
  djanghi-api:
    build:
      context: .
    image: djanghi/prod
    command: gunicorn apps.wsgi:application --bind 0.0.0.0:8070 -w 5
    volumes:
      - static_volume:/var/djanghi/static
    expose:
      - "8070"
    networks:
      - djanghi-network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/djanghi/static
    ports:
      - "8080:80"
    depends_on:
      - djanghi-api
    networks:
      - djanghi-network

networks:
  djanghi-network:
    name: djanghi-network

volumes:
  static_volume:
